### ISSUE TITLE
UI: Touchscreen typing & share problems

### ISSUE THREAD

**Issue by lukephills** [BlokDust/BlokDust#143]
1. Can't type text into the 'Title' field when sharing

2. Can't type text into Search soundcloud boxes.

2. Click to copy unique share URL does nothing

**Comment by Whitevinyl** [comment]
touch on share doesn't highlight - default behaviour not there

**Comment by Whitevinyl** [comment]
I've completely reworked how I do both of these, the title is a real text input now. @lukephills @edsilv could you test the Share panel on ipad/touch?

Things to test:

- Typing the title
- generating the title
- creating a save and clicking the URL box to select/copy

Hoping the typing and single click selection work, once it's finished will apply it to the soundcloud search as well. This way will give a lot more typing control as well, and I've allowed some punctuation and stripped naughty ones.

**Comment by lukephills** [comment]
Share panel isn't working for me.

1. Font size pixel ratio bug 
2. Pressing on title text does nothing
3. URL can be generated but when you tap the URL box nothing happens

![img_0276](https://cloud.githubusercontent.com/assets/6436772/14628949/bfca8b00-0656-11e6-9b44-1126ab65600b.jpg)

**Comment by Whitevinyl** [comment]
Ah ok, so the non-canvas touch stuff isn't working because we're calling preventDefault in the pointer manager on all touch events. I'll see if I can add a case for that.

Font should be fixed.

**Comment by Whitevinyl** [comment]
OK I _think_ this is gonna work now, have pushed an update with a touch target fix.

**Comment by lukephills** [comment]
You're getting there! A few little problems still though

- Size is correct

- Typing brings up native keyboard

- Letters and numbers work

- Foreign letters / accents work 
(although some rare characters show in a different font, probably because they're not available)

- All punctuation doesn't show, apart from these characters:
! [ ] _ € … 

BUG:  On closing the keyboard screen the app doesn't resize properly. See image below.

BUG: When the keyboard is open, and you've typed your title. Pressing generate share link does nothing. If you press generate share link on the right hand side the title will randomise. I think this is to do with the resize issue because even if you close the keyboard the hitpoints are off.

BUG: (pressing slightly below the button) Generate share link draws the arrow underneath but nothing happens. This is the same on desktop.

HALF BUG: Pressing 'Go' (enter button) on the keyboard doesn't do anything. Should perhaps at very least close the keyboard if not also generate the share link. Currently the only way to get out of the keyboard screen is by tapping the keyboard close button in the bottom right corner. The textbox should lose focus if we press elsewhere on the screen.

**Comment by lukephills** [comment]
See the black rectangle at the bottom

![img_0277](https://cloud.githubusercontent.com/assets/6436772/14658635/8166dc7c-06e9-11e6-9c23-d642d1096e99.PNG)

**Comment by lukephills** [comment]
Typing in the text box feels much nicer now though. I like that I can select the whole text and delete

**Comment by Whitevinyl** [comment]
OK cool, thanks for this, will have to test on a device myself in the next week or so, but I think I know what's happening.

The keyboard opening doesn't resize the page, but scrolls it up. Our App hit-tests are based on screen position. Probably need to explore a CSS fix for this. As well as fixing it, probably worth adding scroll position to our hit testing as a safety. ref:
http://stackoverflow.com/questions/10619438/prevent-movement-of-user-inteface-when-keyboard-appears

The Enter event and clicking on the app both need to cal blur() on the input.

The bit that has me stumped though is clicking below the generate button, I don't seem to be able to recreate it, so I would think a PixelRatio thing, but I can't recreate it using simulated pixel ratio in Chrome's device emulation. Is that the only button to do it?

Did you test selecting/copying the URL?

**Comment by lukephills** [comment]
I'm not sure it's a pixelRatio thing because the x coordinate seems correct but the y coordinate is off by about the same amount as the black rectangle. I think it's probably due to scrolling the screen up? 

It's the same for Overwrite and create new buttons. When I'm pressing generate on the right hand side it. It's actually hitting the randomize.

Hang on, I was trying to save without any blocks hence it wasn't bring up the URL. Generate link is working and a URL does come up. I can press on it and and select a section but the URL is too long to fit in the box so it's impossible to select the whole thing. Dragging the far right side cancels the selection instead of scrolling the text to the left.

**Comment by Whitevinyl** [comment]
It should one-click select all, but it seems this isn't implemented in ios Safari.
http://stackoverflow.com/questions/22045802/on-safari-mobile-auto-select-all-the-text-of-a-read-only-input-on-focus
http://stackoverflow.com/questions/3272089/programmatically-selecting-text-in-an-input-field-on-ios-devices-mobile-safari

Will have to try some other workaround.

**Comment by Whitevinyl** [comment]
Fresh to-do list:
-[ ] add vertical page scroll to click/touch positioning in input manager
-[ ] fix page position after touch keyboard is closed (CSS/JS)
-[ ] go/enter closes the keyboard (doing action wouldn't work with new/overwrite)
-[ ] make url text touch selectable with double-click
-[ ] if possible, make url one-click selectable in safari

**Comment by Whitevinyl** [comment]
Hey @lukephills have pushed some new things to check:

- [ ] hit-tests on retina, check that button hit-boxes are where they should be, both before and after the virtual keyboard has been open
- [ ] see if the go/enter button closes the keyboard on the share screen, and performs a search in the sc search screen
- [ ] see if the page returns to it's original position after the keyboard is closed, and there's no black bar at the bottom of the screen
- [ ] see if selecting the URL in the share panel lets you scroll the box so that the whole URL can be selected

**Comment by lukephills** [comment]
Hey @Whitevinyl, nice work 3 out of 4! 

You can scroll along the x axis to see the full url but you can't select it all. I can try, but as soon as i   'touchUp' the text becomes unselected. 

Perhaps we can force the text to be preselected by doing something like [this](http://stackoverflow.com/a/6431441/3102591)

**Comment by Whitevinyl** [comment]
Ah cool, have just pushed a version using selectionStart / End, see if that works!

Might have to tweak which function calls it (currently onClick) but yeah it looks like this is the way

**Comment by lukephills** [comment]
Nailed it!
